# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('year', models.IntegerField()),
                ('university', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
