# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='slug',
        ),
    ]
