# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_remove_personaldetail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
