# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_personaldetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
